###########################################################################################
#
#  STATAMIC CUSTOM ROUTES
#
###########################################################################################

routes:

	/products/debrisoft: debrisoft

ignore:
  # - success
