###########################################################################################
#
#  STATAMIC CUSTOM ROUTES
#
###########################################################################################

routes:

	/products/debrisoft: debrisoft
	/products/flivasorb: flivasorb
	/products/suprasorb: suprasorb
	/products/actiformcool: actiformcool

ignore:
  # - success
